import os
import sysconfig

def getCurrentWorkingDirectory() -> str:
    return os.getcwd()

# DESCRIPTION: Determine the host operating system for host system/target  
# system specific compilation settings
# REMARK: Processig done so that host operating system identifier string 
# generated by sysconfig matches the target platform string convention used
# E. g. "linux-x86_64" -> "linux.x86_64", "win-amd64" -> "windows.amd64"
def getHostPlatform() -> str:
    _tmp_hostPlatform : str = sysconfig.get_platform()
    _tmp_hostPlatform = _tmp_hostPlatform.replace("-", ".") 
    _tmp_hostPlatform = _tmp_hostPlatform.replace("win", "windows")

    return _tmp_hostPlatform